### ISSUE TITLE
Username and password fields repeatedly autofill with wrong values

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_webservices#5]
The username and password fields repeatedly autofill with my REDCap username and password.  This is really annoying when the fields are supposed to be blank. 

Could their field names be changes to something like webservice_username and webservice_password so they won't autofill when the should be blank?

See https://github.com/ctsit/redcap_webservices/blob/be9f65d8e0b4a83590509304c04c032b9de30082/config.json#L39

**Comment by tbembersimeao** [comment]
@pbchase fixed here: #6.
